audit_header: false
title: Maui Real Estate Video Blog with Fred Romvari
description: Our mission at The Romvari Group is to be your best resource for Maui real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Romvari Group, your professional Maui Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Fred Romvari
  title:
  license_number:
  about_markdown: |
    With Fred Romvari, you place your trust in an expert, not just an agent. As a real estate professional with an innate ability to see the “big picture,” Fred Romvari is uniquely qualified to meet—and exceed—your specific needs and expectations. With more than 28 years of experience in the industry, Fred offers unrivaled expertise and market knowledge, and he is highly regarded for his negotiating skills, strategic vision and consummate professionalism.  
  market: Maui
  brand: The Romvari Group
  brokerage: Coldwell Banker Island Properties
  address: 3750 Wailea Alanui Dr. B-35<BR>Wailea, HI 96753
  phone: 808-870-4321
  phone_type:
  phone2:
  phone2_type:
  email: Sara@romvari.net
  url: https://www.MauiJustListed.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.mauijustlisted.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.mauijustlisted.com/search/results/?region=Central&region=East&region=N.+Shore&region=South&region=Upcountry&region=West&neighborhood=all&type=res&list_price_min=50000&list_price_max=all&beds_min=all&baths_min=all&area_min=all&ohana=all&water_front=all&view=all&year_built_min=all&pool=all&sort_latest=true

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your Maui Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.mauijustlisted.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a Maui Home?"
    CTA_text2: "Search the entire MLS for your Maui home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.mauijustlisted.com/search/results/?region=Central&region=East&region=N.+Shore&region=South&region=Upcountry&region=West&neighborhood=all&type=res&list_price_min=50000&list_price_max=all&beds_min=all&baths_min=all&area_min=all&ohana=all&water_front=all&view=all&year_built_min=all&pool=all&sort_latest=true

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: http://www.facebook.com/mauilivingnow
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/The-Romvari-Group/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Maui Real Estate Podcast with Fred Romvari'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Maui Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Romvari Group - your professional Maui Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Maui, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Fred Romvari'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Maui Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#005295'
  theme_color: '#d5a32c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
